/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Carlos
 */
public class Genio extends javax.swing.JFrame {

    /**
     * Creates new form Genio
     */
    public Genio() {
        initComponents();
        
        lblFrase.setText("<html>Vou pensar em um valor entre 1 e 5. Tente Adivinhar </html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFrase = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblVal = new javax.swing.JLabel();
        txtVal = new javax.swing.JSpinner();
        btnPalpipte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFrase.setBackground(new java.awt.Color(0, 0, 0));
        lblFrase.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFrase.setForeground(new java.awt.Color(0, 0, 0));
        lblFrase.setText("CCC");
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 250, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/111.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 10, 440, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/11genio.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 351, -1));

        lblVal.setText("Valor");
        getContentPane().add(lblVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 20));

        txtVal.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(txtVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 100, -1));

        btnPalpipte.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPalpipte.setText("Palpite");
        btnPalpipte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpipteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalpipte, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpipteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpipteActionPerformed
        // TODO add your handling code here:
        double m = 1 + Math.random() * (6-1);
        int valor = (int) m;
        
        int num = Integer.parseInt(txtVal.getValue().toString());
        
        String f1 = "<html>Acertou</html>";
        String f2 = "<html> ERROU, eu pensei no valor " + valor + "</html>";
        
        String res = valor == num ? f1:f2;
        
        lblFrase.setText(res);
    }//GEN-LAST:event_btnPalpipteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Genio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpipte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblVal;
    private javax.swing.JSpinner txtVal;
    // End of variables declaration//GEN-END:variables
}
